name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.sys.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.10.7", "9.2.8", "9.4.5", "9.6.2"]
        cabal: ["3.10.1.0"]
        sys:
          - { os: windows-latest, shell: 'C:/msys64/usr/bin/bash.exe -e {0}' }
          - { os: ubuntu-latest, shell: bash }
          - { os: macos-latest, shell: bash}

    defaults:
        run:
          shell: ${{ matrix.sys.shell }}

    steps:
    - name: Setup Base
      uses: input-output-hk/actions/base@latest
      with:
        use-sodium-vrf: false

    - name: Setup Haskell
      id: setup-haskell
      uses: input-output-hk/actions/haskell@latest
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: "Install system dependencies (apt-get)"
      if: runner.os == 'Linux'
      run: |
        sudo apt-get -y install liblmdb-dev

    - name: "MacOS: Install system dependencies (brew)"
      if: runner.os == 'macOS'
      run: |
        brew install lmdb
        sudo cp ./.github/workflows/lmdb.pc /usr/local/lib/pkgconfig

    - name: "Windows: Install system dependencies via pacman (msys2)"
      if: runner.os == 'Windows'
      run: |
        /usr/bin/pacman --noconfirm -S mingw-w64-x86_64-lmdb

    - name: "Configure cabal.project.local"
      run: |
        cp .github/workflows/cabal.project.local cabal.project.local

    - name: Cabal update
      run: cabal update

    - name: Record cabal dependencies
      id: record-deps
      run: |
        cabal build all --dry-run

    - name: Cache cabal store
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc }}-build-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}-

    - name: Install cabal dependencies
      run: cabal build --only-dependencies --enable-tests --enable-benchmarks all

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all

    - name: Run tests
      run: cabal test all
